export const productsData = [
  { 
    slug: "cd-1", 
    img_url: "/src/backend/media/images/products/cd_1.jpg",
    img_alt: "Scelerisque purus semper ",
    name: "De vilda",
    short_desc: "Latest CD",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Molestie at elementum eu facilisis. Scelerisque purus semper eget duis at tellus at.",
    additional_info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    type: "music",
    stock: 5,
    price: 180 
  },
  { 
    slug: "cd-2", 
    img_url: "/src/backend/media/images/products/cd_2.jpg",
    img_alt: "ed do eiusmod",
    name: "Samiräverin",
    short_desc: "The oldest CD",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Molestie at elementum eu facilisis. Scelerisque purus semper eget duis at tellus at.",
    additional_info: "",
    type: "music",
    stock: 5,
    price: 145 
  },
  {
    slug: "ep-1",
    img_url: "/src/backend/media/images/products/ep_1.jpg",
    img_alt: "ut labore et",
    name: "Ensamheten",
    short_desc: "Latest EP",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nibh mauris cursus mattis molestie a iaculis. Et leo duis ut diam quam.",
    additional_info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    type: "music",
    stock: 0,
    price: 120 
  },
  {
    slug: "ep-2",
    img_url: "/src/backend/media/images/products/ep_2.jpg",
    img_alt: "Vestibulum morbi blandit cursus",
    name: "Sjuhundra",
    short_desc: "Latest EP",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Neque laoreet suspendisse interdum consectetur libero slug.",
    additional_info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    type: "music",
    stock: 7,
    price: 117
  },
  {
    slug: "hat-1",
    img_url: "/src/backend/media/images/products/hat_1.jpg",
    img_alt: "Accumsan in nisl nisi scelerisque",
    name: "Blåräv Poofball hat",
    short_desc: "Wear it on a cold day",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Consectetur purus ut faucibus pulvinar elementum integer enim neque.",
    additional_info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    type: "clothing",
    stock: 6,
    price: 95 
  },
  {
    slug: "hat-2",
    img_url: "/src/backend/media/images/products/hat_2.jpg",
    img_alt: "Amet consectetur adipiscing elit",
    name: "Blåräv Baseball Hat #1",
    short_desc: "Wear it on a sunny day",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Consectetur purus ut faucibus pulvinar elementum integer enim neque.",
    additional_info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    type: "clothing",
    stock: 3,
    price: 105 
  },
  {
    slug: "hat-3",
    img_url: "/src/backend/media/images/products/hat_3.jpg",
    img_alt: "Amet consectetur adipiscing elit",
    name: "Blåräv Baseball Hat #2",
    short_desc: "Patch included!",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Consectetur purus ut faucibus pulvinar elementum integer enim neque.",
    additional_info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    type: "clothing",
    stock: 2,
    price: 125
  },
  { 
    slug: "lp-1",
    img_url: "/src/backend/media/images/products/lp_1.jpg",
    img_alt: "#",
    name: "När världen faller",
    short_desc: "Latest LP",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Turpis tincidunt slug aliquet risus feugiat in ante metus dictum. Euismod nisi porta lorem mollis aliquam ut.",
    additional_info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    type: "music",
    stock: 6,
    price: 235 
  },
  { 
    slug: "mug-1", 
    img_url: "/src/backend/media/images/products/mug_1.jpg",
    img_alt: "Tempor orci dapibus ultrices in iaculis",
    name: "Blåräv Coffee Mug #1",
    short_desc: "Drink and enjoy",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Cursus sit amet dictum sit amet. Senectus et netus et malesuada fames ac turpis egestas maecenas.",
    additional_info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    type: "accessories",
    stock: 2,
    price: 75 
  },
  { 
    slug: "mug-2", 
    img_url: "/src/backend/media/images/products/mug_2.jpg",
    img_alt: "Adipiscing diam donec adipiscing tristique risus",
    name: "Blåräv Coffee Mug #2",
    short_desc: "Drink and enjoy",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris nunc congue nisi.",
    additional_info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    type: "accessories",
    stock: 0,
    price: 85 
  },
  { 
    slug: "patch-1", 
    img_url: "/src/backend/media/images/products/patch_1.jpg",
    img_alt: "Adipiscing diam donec adipiscing tristique risus",
    name: "Blåräv Patch #1",
    short_desc: "Stitches that are fun",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Amet risus nullam eget felis.",
    additional_info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    type: "accessories",
    stock: 7,
    price: 50,
  },
  { 
    slug: "patch-2", 
    img_url: "/src/backend/media/images/products/patch_2.jpg",
    img_alt: "Adipiscing diam donec adipiscing tristique risus",
    name: "Blåräv patch #2",
    short_desc: "Stitches that are fun",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Amet risus nullam eget felis.",
    additional_info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    type: "accessories",
    stock: 7,
    price: 39 
  },
  { 
    slug: "print-1", 
    img_url: "/src/backend/media/images/products/print_1.jpg",
    img_alt: "Adipiscing diam donec adipiscing tristique risus",
    name: "Blåräv Print #1",
    short_desc: "Poster from the 'En för en' tour",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis auctor elit sed vulputate mi sit amet.",
    additional_info: "40 x 40 cm",
    type: "print",
    stock: 2,
    price: 118 
  },
  { 
    slug: "print-2", img_url: "/src/backend/media/images/products/print_2.jpg",
    img_alt: "Adipiscing diam donec adipiscing tristique risus",
    name: "Blåräv Print #2",
    short_desc: "Poster for the 2023-03-25 show",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis auctor elit sed vulputate mi sit amet.",
    additional_info: "40 x 40 cm",
    type: "print",
    stock: 3,
    price: 137 
  },
  { 
    slug: "print-3", 
    img_url: "/src/backend/media/images/products/print_3.jpg",
    img_alt: "Adipiscing diam donec adipiscing tristique risus",
    name: "Blåräv Print #3",
    short_desc: "Poster for the 2023-05-18 show",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis auctor elit sed vulputate mi sit amet.",
    additional_info: "40 x 20 cm",
    type: "print",
    stock: 5,
    price: 105 
  },
  { 
    slug: "shirt-1",
    img_url: "/src/backend/media/images/products/t-shirt_1.jpg",
    img_alt: "#",
    name: "Blåräv t-shirt #1",
    short_desc: "Comes in various sizes",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Potenti nullam ac tortor vitae purus. Volutpat odio facilisis mauris sit amet massa vitae tortor condimentum.",
    additional_info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    type: "clothing",
    stock: 8,
    price: 111
  },
  { 
    slug: "shirt-2",
    img_url: "/src/backend/media/images/products/t-shirt_2.jpg",
    img_alt: "#",
    name: "Blåräv t-shirt #2",
    short_desc: "Comes in various sizes",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Potenti nullam ac tortor vitae purus. Volutpat odio facilisis mauris sit amet massa vitae tortor condimentum.",
    additional_info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    type: "clothing",
    stock: 4,
    price: 133 
  },
];